@extends('admin.layout.app', ['title' => 'Cash Flow'])

@section('content')

    <div class="sec-hdr">
        <div>
            <h2>Cash Flow</h2>
            <div class="sec-sub">Direct-method statement of cash movements, built from posted Journal Entries</div>
        </div>
    </div>

    <div class="tl-toolbar mb-3">
        <form method="GET" class="d-flex gap-2 flex-wrap align-items-center w-100">
            <input type="date" name="date_from" class="form-control form-control-sm w-auto" value="{{ $dateFrom }}" onchange="this.form.submit()" placeholder="From">
            <input type="date" name="date_to" class="form-control form-control-sm w-auto" value="{{ $dateTo }}" onchange="this.form.submit()" placeholder="To">

            @if($dateFrom || $dateTo)
                <a href="{{ route('admin.cash-flow.index') }}" class="btn-nx-outline btn-sm">
                    <i class="ri-close-line"></i> Clear Filters
                </a>
            @endif
        </form>
    </div>

    @if($cashAccounts->isEmpty())

        <div class="nx-card">
            <div class="nx-card-body">
                <div class="text-muted">
                    No Cash or Bank accounts have been set up yet. A cash account is a postable
                    <strong>asset</strong> account whose Account Type is named something containing
                    &ldquo;Cash&rdquo; or &ldquo;Bank&rdquo;.
                    Create one under <a href="{{ route('admin.account-types.index') }}">Account Types</a>,
                    then assign it to an account in the <a href="{{ route('admin.chart-of-accounts.index') }}">Chart of Accounts</a>.
                </div>
            </div>
        </div>

    @else

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-content">
                    <div class="stat-lbl">Operating Activities</div>
                    <div class="stat-val {{ $totalOperating < 0 ? 'text-danger' : '' }}">{{ number_format($totalOperating, 2) }}</div>
                </div>
                <div class="stat-icon-wrap si-green">
                    <i class="ri-exchange-dollar-line"></i>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-content">
                    <div class="stat-lbl">Investing Activities</div>
                    <div class="stat-val {{ $totalInvesting < 0 ? 'text-danger' : '' }}">{{ number_format($totalInvesting, 2) }}</div>
                </div>
                <div class="stat-icon-wrap si-amber">
                    <i class="ri-building-line"></i>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-content">
                    <div class="stat-lbl">Financing Activities</div>
                    <div class="stat-val {{ $totalFinancing < 0 ? 'text-danger' : '' }}">{{ number_format($totalFinancing, 2) }}</div>
                </div>
                <div class="stat-icon-wrap si-blue">
                    <i class="ri-bank-line"></i>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-content">
                    <div class="stat-lbl">Closing Cash</div>
                    <div class="stat-val {{ $closingBalance < 0 ? 'text-danger' : '' }}">{{ number_format($closingBalance, 2) }}</div>
                </div>
                <div class="stat-icon-wrap si-purple">
                    <i class="ri-safe-2-line"></i>
                </div>
            </div>
        </div>

        @php
            $sections = [
                ['title' => 'Operating Activities', 'sub' => 'Cash from day-to-day trading (revenue and expense accounts)', 'rows' => $operating, 'total' => $totalOperating],
                ['title' => 'Investing Activities', 'sub' => 'Cash used for or generated by other assets', 'rows' => $investing, 'total' => $totalInvesting],
                ['title' => 'Financing Activities', 'sub' => 'Cash from liabilities and equity — how the business is funded', 'rows' => $financing, 'total' => $totalFinancing],
            ];
        @endphp

        @foreach($sections as $section)
            <div class="nx-card">
                <div class="nx-card-hdr">
                    <div>
                        <div class="nx-card-title">{{ $section['title'] }}</div>
                        <div class="nx-card-sub">{{ $section['sub'] }}</div>
                    </div>
                </div>

                <div class="nx-card-body">
                    <div style="overflow-x:auto;">
                        <table class="ractivity-tbl">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Source / Use of Cash</th>
                                    <th class="text-end">Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($section['rows'] as $row)
                                    <tr>
                                        <td>{{ $row['code'] }}</td>
                                        <td>
                                            <a href="{{ route('admin.general-ledger.index', array_filter(['account_id' => $row['account_id'], 'date_from' => $dateFrom, 'date_to' => $dateTo])) }}">{{ $row['name'] }}</a>
                                        </td>
                                        <td class="text-end {{ $row['amount'] < 0 ? 'text-danger' : '' }}">{{ number_format($row['amount'], 2) }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3" class="text-center text-muted">No cash movement in this category for the selected period</td>
                                    </tr>
                                @endforelse
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th colspan="2" class="text-end">Net Cash from {{ $section['title'] }}</th>
                                    <th class="text-end {{ $section['total'] < 0 ? 'text-danger' : '' }}">{{ number_format($section['total'], 2) }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        @endforeach

        <div class="nx-card">
            <div class="nx-card-hdr">
                <div>
                    <div class="nx-card-title">Cash Reconciliation</div>
                    <div class="nx-card-sub">Opening cash plus net movement should equal the cash accounts' own closing balance</div>
                </div>
            </div>

            <div class="nx-card-body">
                <table class="ractivity-tbl">
                    <tbody>
                        <tr>
                            <td>Opening Cash Balance</td>
                            <td class="text-end">{{ number_format($openingBalance, 2) }}</td>
                        </tr>
                        <tr>
                            <td>Net Cash from Operating Activities</td>
                            <td class="text-end {{ $totalOperating < 0 ? 'text-danger' : '' }}">{{ number_format($totalOperating, 2) }}</td>
                        </tr>
                        <tr>
                            <td>Net Cash from Investing Activities</td>
                            <td class="text-end {{ $totalInvesting < 0 ? 'text-danger' : '' }}">{{ number_format($totalInvesting, 2) }}</td>
                        </tr>
                        <tr>
                            <td>Net Cash from Financing Activities</td>
                            <td class="text-end {{ $totalFinancing < 0 ? 'text-danger' : '' }}">{{ number_format($totalFinancing, 2) }}</td>
                        </tr>
                        <tr>
                            <td><em>Net Change in Cash</em></td>
                            <td class="text-end {{ $netChange < 0 ? 'text-danger' : '' }}"><em>{{ number_format($netChange, 2) }}</em></td>
                        </tr>
                        <tr>
                            <th>Closing Cash Balance</th>
                            <th class="text-end {{ $isReconciled ? '' : 'text-danger' }}">{{ number_format($closingBalance, 2) }}</th>
                        </tr>
                    </tbody>
                </table>

                @unless($isReconciled)
                    <div class="text-danger mt-3">
                        <i class="ri-error-warning-line"></i>
                        <strong>Does not reconcile — off by {{ number_format($reconciliationDifference, 2) }}.</strong>
                        The cash accounts' own balance at this date is {{ number_format($actualClosing, 2) }}.
                        @if(abs($unclassified) > 0.001)
                            {{ number_format($unclassified, 2) }} of cash movement could not be attributed to any non-cash account.
                        @endif
                        Review the Cash Book and Trial Balance for the affected postings.
                    </div>
                @endunless
            </div>
        </div>

    @endif

@endsection
