<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // A history log of every time a ticket was actually escalated —
        // system-generated by the "Escalate" quick action, never hand-
        // entered, the same "real persisted history, not just an activity
        // log line" reasoning Ticket Assignment already established for its
        // own table. `escalation_rule_id` is nullOnDelete so the historical
        // record survives a rule being edited/removed later; the priority
        // snapshot columns and the resolved agent are captured at the
        // moment of escalation, independent of whatever the rule itself
        // says today.
        Schema::create('ticket_escalations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('ticket_id')->constrained('tickets')->cascadeOnDelete();
            $table->foreignId('escalation_rule_id')->nullable()->constrained('escalation_rules')->nullOnDelete();
            $table->dateTime('escalated_at');
            $table->foreignId('escalated_to_admin_id')->nullable()->constrained('admins')->nullOnDelete();
            $table->enum('previous_priority', ['low', 'medium', 'high', 'urgent'])->nullable();
            $table->enum('new_priority', ['low', 'medium', 'high', 'urgent'])->nullable();
            $table->text('notes')->nullable();
            $table->boolean('status')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('ticket_escalations');
    }
};
