<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\EscalationRule;
use App\Models\Ticket;
use App\Models\TicketEscalation;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class TicketEscalationController extends Controller
{
    /**
     * Escalation History — a read-only log of every time a ticket was
     * actually escalated. No create/edit/delete: these records are
     * system-generated by the "Escalate" quick action on Tickets, never
     * hand-entered, the same "controller only, index-only" shape used by
     * every read-only report in this project (e.g. Employee Asset
     * Tracking).
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = TicketEscalation::with(['ticket', 'escalationRule', 'escalatedToAdmin']);

            if ($request->status) {
                $statuses = explode(',', $request->status);
                $query->whereIn('status', $statuses);
            }

            if ($request->ticket_id) {
                $query->where('ticket_id', $request->ticket_id);
            }

            if ($request->escalation_rule_id) {
                $query->where('escalation_rule_id', $request->escalation_rule_id);
            }

            if ($request->search) {
                $search = $request->search;
                $query->whereHas('ticket', function ($q) use ($search) {
                    $q->where('subject', 'like', "%{$search}%")
                        ->orWhere('ticket_number', 'like', "%{$search}%");
                });
            }

            $query->orderBy('escalated_at', 'DESC');

            return DataTables::eloquent($query)
                ->addColumn('status_badge', function ($row) {
                    return '<span class="badge ' . ($row->status ? 'bg-success' : 'bg-secondary') . '">' . ($row->status ? 'Active' : 'Inactive') . '</span>';
                })
                ->addColumn('ticket_col', function ($row) {
                    if (! $row->ticket) {
                        return '<span class="text-danger">Ticket removed</span>';
                    }

                    return '<b class="tl-name-txt">' . e($row->ticket->subject) . '</b><br><small>' . e($row->ticket->ticket_number) . '</small>';
                })
                ->addColumn('rule_col', function ($row) {
                    return $row->escalationRule
                        ? e($row->escalationRule->name)
                        : '<span class="text-muted">Rule removed</span>';
                })
                ->addColumn('priority_change_col', function ($row) {
                    if (! $row->previous_priority || ! $row->new_priority || $row->previous_priority === $row->new_priority) {
                        return '<span class="text-muted">Unchanged</span>';
                    }

                    return ucfirst($row->previous_priority) . ' → ' . ucfirst($row->new_priority);
                })
                ->addColumn('escalated_to_col', function ($row) {
                    return $row->escalatedToAdmin
                        ? e($row->escalatedToAdmin->name)
                        : '<span class="text-muted">—</span>';
                })
                ->addColumn('escalated_at_formatted', function ($row) {
                    return $row->escalated_at->format('d M Y, H:i');
                })
                ->rawColumns(['status_badge', 'ticket_col', 'rule_col', 'priority_change_col', 'escalated_to_col'])
                ->make(true);
        }

        return view('admin.ticket-escalations.index', [
            'tickets' => Ticket::active()->orderBy('ticket_number')->get(),
            'rules' => EscalationRule::active()->orderBy('name')->get(),
        ]);
    }
}
